spring:
  application:
    name: devPortes-Backend

  datasource:
    url: jdbc:postgresql://localhost:5432/golaya_db
    username: postgres
    password: Chitiva_09
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

logging:
  level:
    root: INFO
    com.devPortes: DEBUG

    org.hibernate.SQL: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

    org.springframework.security: DEBUG
    org.springframework: WARN
    org.hibernate: WARN

  pattern:
    console: "%clr(%d{HH:mm:ss}){faint} %clr(%-5level) %clr(%logger{36}){cyan} %clr(:){faint} %msg%n"

api:
  security:
    token:
      secret: ${JWT_SECRET:123456789}
      expiration: 86400

app:
  cors:
    allowed-origins: http://localhost:5500:http://localhost:3000